export { default as HomePage } from './HomePage'
export { default as LoginPage } from './LoginPage'
export { default as SignUpPage } from './SignUpPage'
export { default as SearchPage } from './SearchPage'
export { default as DetailPage } from './DetailPage'
export { default as NotFoundPage } from './NotFoundPage'
